services:
  api: 
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 8080:8080

  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
volumes:
  db-store:
