HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Vary: Origin, X-Origin, Referer
Content-Encoding: gzip
Date: Mon, 03 Feb 2025 11:19:39 GMT
Server: ESF
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Connection: close
Transfer-Encoding: chunked

{
  "kind": "books#volumes",
  "totalItems": 824,
  "items": [
    {
      "kind": "books#volume",
      "id": "HDBNDwAAQBAJ",
      "etag": "wW0eKrHsjYw",
      "selfLink": "https://www.googleapis.com/books/v1/volumes/HDBNDwAAQBAJ",
      "volumeInfo": {
        "title": "「進撃の巨人」超考察",
        "authors": [
          "日本コミック研究所"
        ],
        "publisher": "ベストセラーズ",
        "publishedDate": "2011-06-24",
        "description": "大人気コミックス、『進撃の巨人』(講談社刊)の非公式、考察本。 伏線考察から、世界中の巨人伝説、神話などを解説し、その世界観のモデルになっていると思われる歴史、雑学などを紹介！ 「巨人が人を食う」衝撃の世界観を徹底分析！ ●巨人の謎はすでに解かれている！？ ●カギは単行本にある？カバーの裏に隠された、秘密のメッセージとは？ ●巨人はいったい何なのか？ 最大の謎を徹底解説！！ ●ぼくらの先祖も巨人に会っていた！？世界中の巨人にまつわる神話を一挙に紹介！！ ●北欧神話を知ればストーリーの行方がわかる！？「ユミル」ってナンだ！？ ●人類を閉じ込める壁の存在とは？ 壁は人類が造ったモノなのか？",
        "industryIdentifiers": [
          {
            "type": "OTHER",
            "identifier": "PKEY:BT000024041600100101900209"
          }
        ],
        "readingModes": {
          "text": true,
          "image": true
        },
        "pageCount": 104,
        "printType": "BOOK",
        "categories": [
          "Social Science"
        ],
        "maturityRating": "NOT_MATURE",
        "allowAnonLogging": false,
        "contentVersion": "1.2.3.0.preview.3",
        "panelizationSummary": {
          "containsEpubBubbles": false,
          "containsImageBubbles": false
        },
        "imageLinks": {
          "smallThumbnail": "http://books.google.com/books/content?id=HDBNDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
          "thumbnail": "http://books.google.com/books/content?id=HDBNDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        },
        "language": "ja",
        "previewLink": "http://books.google.co.jp/books?id=HDBNDwAAQBAJ&pg=PP3&dq=%E9%80%B2%E6%92%83%E3%81%AE&hl=&cd=1&source=gbs_api",
        "infoLink": "http://books.google.co.jp/books?id=HDBNDwAAQBAJ&dq=%E9%80%B2%E6%92%83%E3%81%AE&hl=&source=gbs_api",
        "canonicalVolumeLink": "https://books.google.com/books/about/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_%E8%B6%85%E8%80%83%E5%AF%9F.html?hl=&id=HDBNDwAAQBAJ"
      },
      "saleInfo": {
        "country": "JP",
        "saleability": "NOT_FOR_SALE",
        "isEbook": false
      },
      "accessInfo": {
        "country": "JP",
        "viewability": "PARTIAL",
        "embeddable": true,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        "epub": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_%E8%B6%85%E8%80%83%E5%AF%9F-sample-epub.acsm?id=HDBNDwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "pdf": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_%E8%B6%85%E8%80%83%E5%AF%9F-sample-pdf.acsm?id=HDBNDwAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "webReaderLink": "http://play.google.com/books/reader?id=HDBNDwAAQBAJ&hl=&source=gbs_api",
        "accessViewStatus": "SAMPLE",
        "quoteSharingAllowed": false
      },
      "searchInfo": {
        "textSnippet": "... \u003cb\u003e進撃の\u003c/b\u003e巨人』です。これまでの受賞作と比べて、『\u003cb\u003e進撃の\u003c/b\u003e巨人』はけっして知名度が高いと言えず、マンガ好きが熱烈に支持していたものの、幅広いファンを獲得できていなかったように思えます。しかし受賞以降、本作品を目にする機会も増えており、 2011 年&nbsp;..."
      }
    },
    {
      "kind": "books#volume",
      "id": "Bme_FsofHqcC",
      "etag": "amjMnlzLSME",
      "selfLink": "https://www.googleapis.com/books/v1/volumes/Bme_FsofHqcC",
      "volumeInfo": {
        "title": "「進撃の巨人」の秘密エディターズカット版",
        "authors": [
          "『進撃の巨人』研究会"
        ],
        "publisher": "データハウス",
        "publishedDate": "2013-10-01",
        "description": "別冊少年マガジン連載中の超人気コミック『進撃の巨人』の作品世界＆キャラクターを様々に考察・推理した研究本がついに登場！ 巨人、壁、ウォール教…様々な謎に包まれている『進撃の巨人』を楽しむための電子書籍。 ※本書は2011年7月刊行の「進撃の巨人の秘密」の内容を電子書籍用に再編集したものです。 This book tells you about “Attack on Titan”, which is very popular in Japan. You can know about the comic and the characters and so on.",
        "readingModes": {
          "text": true,
          "image": true
        },
        "pageCount": 68,
        "printType": "BOOK",
        "categories": [
          "Social Science"
        ],
        "maturityRating": "NOT_MATURE",
        "allowAnonLogging": true,
        "contentVersion": "1.2.3.0.preview.3",
        "panelizationSummary": {
          "containsEpubBubbles": false,
          "containsImageBubbles": false
        },
        "imageLinks": {
          "smallThumbnail": "http://books.google.com/books/content?id=Bme_FsofHqcC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
          "thumbnail": "http://books.google.com/books/content?id=Bme_FsofHqcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        },
        "language": "ja",
        "previewLink": "http://books.google.co.jp/books?id=Bme_FsofHqcC&pg=PT2&dq=%E9%80%B2%E6%92%83%E3%81%AE&hl=&cd=2&source=gbs_api",
        "infoLink": "https://play.google.com/store/books/details?id=Bme_FsofHqcC&source=gbs_api",
        "canonicalVolumeLink": "https://play.google.com/store/books/details?id=Bme_FsofHqcC"
      },
      "saleInfo": {
        "country": "JP",
        "saleability": "FOR_SALE",
        "isEbook": true,
        "listPrice": {
          "amount": 330,
          "currencyCode": "JPY"
        },
        "retailPrice": {
          "amount": 297,
          "currencyCode": "JPY"
        },
        "buyLink": "https://play.google.com/store/books/details?id=Bme_FsofHqcC&rdid=book-Bme_FsofHqcC&rdot=1&source=gbs_api",
        "offers": [
          {
            "finskyOfferType": 1,
            "listPrice": {
              "amountInMicros": 330000000,
              "currencyCode": "JPY"
            },
            "retailPrice": {
              "amountInMicros": 297000000,
              "currencyCode": "JPY"
            }
          }
        ]
      },
      "accessInfo": {
        "country": "JP",
        "viewability": "PARTIAL",
        "embeddable": true,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        "epub": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_%E3%81%AE%E7%A7%98%E5%AF%86%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%83%BC-sample-epub.acsm?id=Bme_FsofHqcC&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "pdf": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_%E3%81%AE%E7%A7%98%E5%AF%86%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%83%BC-sample-pdf.acsm?id=Bme_FsofHqcC&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "webReaderLink": "http://play.google.com/books/reader?id=Bme_FsofHqcC&hl=&source=gbs_api",
        "accessViewStatus": "SAMPLE",
        "quoteSharingAllowed": false
      },
      "searchInfo": {
        "textSnippet": "『\u003cb\u003e進撃の\u003c/b\u003e巨人』研究会. はじめに『\u003cb\u003e進撃の\u003c/b\u003e巨人』という作品は、世に出るとすぐに通な漫画読みたちからの注目を浴び、凄まじい勢いの、まさに快「\u003cb\u003e進撃\u003c/b\u003e」を続けている。本書を手にとっていただいた方ならば、当然ご存知のはずであるが、『\u003cb\u003e進撃の\u003c/b\u003e巨人』は&nbsp;..."
      }
    },
    {
      "kind": "books#volume",
      "id": "Yp0hEAAAQBAJ",
      "etag": "l7YEvMKl7k0",
      "selfLink": "https://www.googleapis.com/books/v1/volumes/Yp0hEAAAQBAJ",
      "volumeInfo": {
        "title": "進撃の巨人　壁外調査最終報告書",
        "authors": [
          "スタジオグリーン編集部"
        ],
        "publisher": "スタジオグリーン",
        "description": "約11年にわたって連載され、世界中のファンを魅了し続けた「進撃の巨人」がついに終焉を迎えようとしている。 エレン、リヴァイ、ミカサたちの運命は？ そして人類の未来はどんな結末を迎えるのか――!? 本書では未だ謎に包まれた世界の秘密と巨人の生態について、原作コミックやアニメ版、小説版などあらゆる作品をヒントに徹底考察し、その真実に迫る！ さらに複雑に絡み合った各世界の歴史や勢力関係を分かりやすくまとめた歴史年表・勢力図・人物相関図など、データ類も満載！ 【もくじ】 「進撃の巨人 ～2000年の刻を超えて～」 第1章 1900年の歴史 第2章 イェーガー派の目的 第3章 エルディア国の目論見 第4章 マーレの野望 第5章 世界の仕組み 第6章 世界の秘密 第7章 用語集 「進撃の巨人 解読の書」 Chapter.01 『進撃の巨人』の世界 Chapter.02 巨人の真理 Chapter.03 人類の考察 Chapter.04 物語の謎 Chapter.05 外の世界の研究 Chapter.06 結末の予測 ※本書は「進撃の巨人 ～2000年の刻を超えて～」(2019年10月)と、「進撃の巨人 解読の書」(2020年2月)を合本化した作品です。",
        "industryIdentifiers": [
          {
            "type": "OTHER",
            "identifier": "PKEY:BT000092027800100101900209"
          }
        ],
        "readingModes": {
          "text": true,
          "image": true
        },
        "pageCount": 389,
        "printType": "BOOK",
        "categories": [
          "Performing Arts"
        ],
        "maturityRating": "NOT_MATURE",
        "allowAnonLogging": false,
        "contentVersion": "1.3.4.0.preview.3",
        "panelizationSummary": {
          "containsEpubBubbles": false,
          "containsImageBubbles": false
        },
        "imageLinks": {
          "smallThumbnail": "http://books.google.com/books/content?id=Yp0hEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
          "thumbnail": "http://books.google.com/books/content?id=Yp0hEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        },
        "language": "ja",
        "previewLink": "http://books.google.co.jp/books?id=Yp0hEAAAQBAJ&pg=PA21-IA36&dq=%E9%80%B2%E6%92%83%E3%81%AE&hl=&cd=3&source=gbs_api",
        "infoLink": "https://play.google.com/store/books/details?id=Yp0hEAAAQBAJ&source=gbs_api",
        "canonicalVolumeLink": "https://play.google.com/store/books/details?id=Yp0hEAAAQBAJ"
      },
      "saleInfo": {
        "country": "JP",
        "saleability": "FOR_SALE",
        "isEbook": true,
        "listPrice": {
          "amount": 501,
          "currencyCode": "JPY"
        },
        "retailPrice": {
          "amount": 501,
          "currencyCode": "JPY"
        },
        "buyLink": "https://play.google.com/store/books/details?id=Yp0hEAAAQBAJ&rdid=book-Yp0hEAAAQBAJ&rdot=1&source=gbs_api",
        "offers": [
          {
            "finskyOfferType": 1,
            "listPrice": {
              "amountInMicros": 501000000,
              "currencyCode": "JPY"
            },
            "retailPrice": {
              "amountInMicros": 501000000,
              "currencyCode": "JPY"
            }
          }
        ]
      },
      "accessInfo": {
        "country": "JP",
        "viewability": "PARTIAL",
        "embeddable": true,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        "epub": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_%E5%A3%81%E5%A4%96%E8%AA%BF%E6%9F%BB%E6%9C%80%E7%B5%82%E5%A0%B1%E5%91%8A-sample-epub.acsm?id=Yp0hEAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "pdf": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_%E5%A3%81%E5%A4%96%E8%AA%BF%E6%9F%BB%E6%9C%80%E7%B5%82%E5%A0%B1%E5%91%8A-sample-pdf.acsm?id=Yp0hEAAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "webReaderLink": "http://play.google.com/books/reader?id=Yp0hEAAAQBAJ&hl=&source=gbs_api",
        "accessViewStatus": "SAMPLE",
        "quoteSharingAllowed": false
      },
      "searchInfo": {
        "textSnippet": "... \u003cb\u003e進撃の\u003c/b\u003e巨人」の世界観と人類の未来とは―壮絶な闘いの末に訪れる関連作品から「\u003cb\u003e進撃の\u003c/b\u003e巨人」の真実に迫る!アニメ版と原作コミックスの「外伝」で明かされたリヴァイの過去相違部分小説版にみる「\u003cb\u003e進撃の\u003c/b\u003e巨人」世界の歴史 ウォール・シーナ直径 500&nbsp;..."
      }
    },
    {
      "kind": "books#volume",
      "id": "L5BnDwAAQBAJ",
      "etag": "/AgjYCJw9c4",
      "selfLink": "https://www.googleapis.com/books/v1/volumes/L5BnDwAAQBAJ",
      "volumeInfo": {
        "title": "初代王の呪縛「進撃の巨人」100年の歴史",
        "authors": [
          "桜山時"
        ],
        "publisher": "サイゾー",
        "publishedDate": "2016-01-15",
        "description": "公式、スピンアウト15作品を大解読!作品の裏表から楽しむポイントを余さず収録。佳境にはいった物語。残された謎を追う。信者/アンチ両視点から作品の魅力を考察!",
        "industryIdentifiers": [
          {
            "type": "OTHER",
            "identifier": "PKEY:CYZOJGP0000000000292"
          }
        ],
        "readingModes": {
          "text": true,
          "image": true
        },
        "pageCount": 121,
        "printType": "BOOK",
        "categories": [
          "Computers"
        ],
        "maturityRating": "NOT_MATURE",
        "allowAnonLogging": false,
        "contentVersion": "1.4.5.0.preview.3",
        "panelizationSummary": {
          "containsEpubBubbles": false,
          "containsImageBubbles": false
        },
        "imageLinks": {
          "smallThumbnail": "http://books.google.com/books/content?id=L5BnDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
          "thumbnail": "http://books.google.com/books/content?id=L5BnDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        },
        "language": "ja",
        "previewLink": "http://books.google.co.jp/books?id=L5BnDwAAQBAJ&pg=PP3&dq=%E9%80%B2%E6%92%83%E3%81%AE&hl=&cd=4&source=gbs_api",
        "infoLink": "https://play.google.com/store/books/details?id=L5BnDwAAQBAJ&source=gbs_api",
        "canonicalVolumeLink": "https://play.google.com/store/books/details?id=L5BnDwAAQBAJ"
      },
      "saleInfo": {
        "country": "JP",
        "saleability": "FOR_SALE",
        "isEbook": true,
        "listPrice": {
          "amount": 1320,
          "currencyCode": "JPY"
        },
        "retailPrice": {
          "amount": 1188,
          "currencyCode": "JPY"
        },
        "buyLink": "https://play.google.com/store/books/details?id=L5BnDwAAQBAJ&rdid=book-L5BnDwAAQBAJ&rdot=1&source=gbs_api",
        "offers": [
          {
            "finskyOfferType": 1,
            "listPrice": {
              "amountInMicros": 1320000000,
              "currencyCode": "JPY"
            },
            "retailPrice": {
              "amountInMicros": 1188000000,
              "currencyCode": "JPY"
            }
          }
        ]
      },
      "accessInfo": {
        "country": "JP",
        "viewability": "PARTIAL",
        "embeddable": true,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        "epub": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E5%88%9D%E4%BB%A3%E7%8E%8B%E3%81%AE%E5%91%AA%E7%B8%9B_%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_100-sample-epub.acsm?id=L5BnDwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "pdf": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E5%88%9D%E4%BB%A3%E7%8E%8B%E3%81%AE%E5%91%AA%E7%B8%9B_%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA_100-sample-pdf.acsm?id=L5BnDwAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "webReaderLink": "http://play.google.com/books/reader?id=L5BnDwAAQBAJ&hl=&source=gbs_api",
        "accessViewStatus": "SAMPLE",
        "quoteSharingAllowed": false
      },
      "searchInfo": {
        "textSnippet": "... \u003cb\u003e進撃の\u003c/b\u003e巨人』は、どうしてここまで売れたのでしょうか?星の数ほどある漫画に比べて、何が優れていたのか、何が受け入れられたのか、何処が時代を捉えていたのか?いや、そもそも、それほどに面白い漫画なのだったのでしょうか?もちろん、『\u003cb\u003e進撃の\u003c/b\u003e巨人』を&nbsp;..."
      }
    },
    {
      "kind": "books#volume",
      "id": "z9mqEAAAQBAJ",
      "etag": "cKrSuVxsVQo",
      "selfLink": "https://www.googleapis.com/books/v1/volumes/z9mqEAAAQBAJ",
      "volumeInfo": {
        "title": "進撃の巨人研究解読書 Return&Future",
        "authors": [
          "巨人研究解読班"
        ],
        "publisher": "ブライト出版",
        "publishedDate": "2014-07-31",
        "description": "なぜ『進撃の巨人』はおもしろいのか。登場人物から各話の深みを知ることで人類未来を予想する研究解説！！ 進撃の巨人の内容をもっと理解する予想したくなる面白さ！！ 巨人を駆逐できるのか…人類は生き残れるのか…原作を読めば読むほど内容をもっと知りたい！！",
        "industryIdentifiers": [
          {
            "type": "OTHER",
            "identifier": "PKEY:BT000029960600100101900209"
          }
        ],
        "readingModes": {
          "text": true,
          "image": true
        },
        "pageCount": 169,
        "printType": "BOOK",
        "categories": [
          "Fiction"
        ],
        "maturityRating": "NOT_MATURE",
        "allowAnonLogging": false,
        "contentVersion": "1.2.3.0.preview.3",
        "panelizationSummary": {
          "containsEpubBubbles": false,
          "containsImageBubbles": false
        },
        "imageLinks": {
          "smallThumbnail": "http://books.google.com/books/content?id=z9mqEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
          "thumbnail": "http://books.google.com/books/content?id=z9mqEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
        },
        "language": "ja",
        "previewLink": "http://books.google.co.jp/books?id=z9mqEAAAQBAJ&pg=PA33&dq=%E9%80%B2%E6%92%83%E3%81%AE&hl=&cd=5&source=gbs_api",
        "infoLink": "https://play.google.com/store/books/details?id=z9mqEAAAQBAJ&source=gbs_api",
        "canonicalVolumeLink": "https://play.google.com/store/books/details?id=z9mqEAAAQBAJ"
      },
      "saleInfo": {
        "country": "JP",
        "saleability": "FOR_SALE",
        "isEbook": true,
        "listPrice": {
          "amount": 943,
          "currencyCode": "JPY"
        },
        "retailPrice": {
          "amount": 849,
          "currencyCode": "JPY"
        },
        "buyLink": "https://play.google.com/store/books/details?id=z9mqEAAAQBAJ&rdid=book-z9mqEAAAQBAJ&rdot=1&source=gbs_api",
        "offers": [
          {
            "finskyOfferType": 1,
            "listPrice": {
              "amountInMicros": 943000000,
              "currencyCode": "JPY"
            },
            "retailPrice": {
              "amountInMicros": 849000000,
              "currencyCode": "JPY"
            }
          }
        ]
      },
      "accessInfo": {
        "country": "JP",
        "viewability": "PARTIAL",
        "embeddable": true,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        "epub": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA%E7%A0%94%E7%A9%B6%E8%A7%A3%E8%AA%AD%E6%9B%B8_Return_Fu-sample-epub.acsm?id=z9mqEAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "pdf": {
          "isAvailable": true,
          "acsTokenLink": "http://books.google.co.jp/books/download/%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA%E7%A0%94%E7%A9%B6%E8%A7%A3%E8%AA%AD%E6%9B%B8_Return_Fu-sample-pdf.acsm?id=z9mqEAAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        "webReaderLink": "http://play.google.com/books/reader?id=z9mqEAAAQBAJ&hl=&source=gbs_api",
        "accessViewStatus": "SAMPLE",
        "quoteSharingAllowed": false
      },
      "searchInfo": {
        "textSnippet": "巨人研究解読班. 突きすすむ!\u003cb\u003e進撃の\u003c/b\u003e巨人考証コラムどんなときでも、恋は生まれる No.3 -ロマンスとしての『\u003cb\u003e進撃の\u003c/b\u003e巨人』悲惨な闘い、厳しい訓練ばかりが続く毎日であっても、それなりに好きだの嫌いだのという浮いた話もあります。だって、みなさんお年頃&nbsp;..."
      }
    }
  ]
}
