name: deploy

on:
  push:
    branches: 
      - main
    paths: 
      - "*.go"
      - "!*_test.go"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST_01: ${{ secrets.SERVER_HOST_01 }}
      SERVER_HOST_02: ${{ secrets.SERVER_HOST_02 }}
      SSH_PRIVATE_KEY_01: ${{ secrets.SSH_PRIVATE_KEY_01}}
      SSH_PRIVATE_KEY_02: ${{ secrets.SSH_PRIVATE_KEY_02}}
    strategy:
      matrix:
        host: [$SERVER_HOST_01, $SERVER_HOST_02]
        key: [$SSH_PRIVATE_KEY_01, $SSH_PRIVATE_KEY_02]
        exclude:
          - host: $SERVER_HOST_01
            key: $SSH_PRIVATE_KEY_02
          - host: $SERVER_HOST_02
            key: $SSH_PRIVATE_KEY_01
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          proxy_passphrase: ${{ secrets.PROXY_PASSPHRASE }}

          host: ${{ matrix.host }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ matrix.key }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          
          script_path: scripts/deploy.sh
