name: Deploy

on:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      contents: read
      actions: read
    environment: prod
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 環境変数の設定
        run: echo "${{ secrets.DOTENV }}" > ${{ github.workspace }}/.env
      
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Resolve dependencies
        run: go mod download
      - name: Build
        run: go clean -cache && go build -o bin/ -trimpath -ldflags "-w -s"
  
      # - name: Upload bin file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gobinfile
      #     path: bin/
      #     if-no-files-found: error
      #     retention-days: 1

      # - name: Download bin file
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: gobinfile
      #     path: bin/
  
      - name: Deploy
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}

          host: ${{ secrets.SERVER_HOST_01 }}, ${{ secrets.SERVER_HOST_02 }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY_01 }}
          source: bin/*
          target: ${{ secrets.SERVER_DEPLOY_DIR }}
      
      - name: Start the servers
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f # v1.2.2
        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}

          host: ${{ secrets.SERVER_HOST_01 }}, ${{ secrets.SERVER_HOST_02 }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY_01 }}
          script: |
            sudo chmod +x ${{ secrets.SERVER_EXECUTE_PATH }}
            nohup ${{ secrets.SERVER_EXECUTE_PATH }} & > "${HOME}/app_$(date '+%Y_%m_%d_%H:%M:%S').log"