name: deploy

on:
  push:
    branches: 
      - main
    paths: 
      - "*.go"
      - "!*_test.go"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: 
          - ${{ secrets.SERVER_HOST_01 }}
          - ${{ secrets.SERVER_HOST_02 }}
        key: 
          - ${{ secrets.SSH_PRIVATE_KEY_01}}
          - ${{ secrets.SSH_PRIVATE_KEY_02}}
        exclude:
          - host: ${{ secrets.SERVER_HOST_01 }}
            key: ${{ secrets.SSH_PRIVATE_KEY_02}}
          - host: ${{ secrets.SERVER_HOST_02 }}
            key: ${{ secrets.SSH_PRIVATE_KEY_01}}
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}

          host: ${{ matrix.host }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ matrix.key }}
          
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main
            go clean -cache && go build -o ~/bin/bhapi -trimpath -ldflags "-w -s"
            chmod +x ~/bin/bhapi
            ~/bin/bhapi
