name: Deploy

on:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      contents: read
      actions: read
    env:
      SERVER_HOST_01: ${{ secrets.SERVER_HOST_01 }}
      SERVER_HOST_02: ${{ secrets.SERVER_HOST_02 }}
      SSH_PRIVATE_KEY_01: ${{ secrets.SSH_PRIVATE_KEY_01}}
      SSH_PRIVATE_KEY_02: ${{ secrets.SSH_PRIVATE_KEY_02}}
    strategy:
      matrix:
        host: [$SERVER_HOST_01, $SERVER_HOST_02]
        key: [$SSH_PRIVATE_KEY_01, $SSH_PRIVATE_KEY_02]
        exclude:
          - host: $SERVER_HOST_01
            key: $SSH_PRIVATE_KEY_02
          - host: $SERVER_HOST_02
            key: $SSH_PRIVATE_KEY_01
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f # v1.2.2
        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          proxy_passphrase: ${{ secrets.PROXY_PASSPHRASE }}

          host: ${{ matrix.host }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ matrix.key }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main
            go mod tidy
            go clean -cache && go build -o ${{ secrets.SERVER_EXECUTE_PATH }} -trimpath -ldflags "-w -s"
            chmod +x ${{ secrets.SERVER_EXECUTE_PATH }}
            nohup ${{ secrets.SERVER_EXECUTE_PATH }} & > "${HOME}/app_$(date '+%Y_%m_%d_%H:%M:%S').log"