name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
    golangci:
        permissions:
            contents: read
            actions: read
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: "1.23.1"
                cache: true
                cache-dependency-path: |
                  **/go.sum
                  **/go.mod
            - name: golangci-lint
              uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
              with:
                version: v2.1
    test:
        needs: golangci
        permissions:
            contents: read
            actions: read
        timeout-minutes: 10
        environment: dev
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: 環境変数の設定
              run: echo "${{ secrets.DOTENV }}" > ${{ github.workspace }}/.env
              
            - uses: actions/setup-go@v5
              with:
                go-version: "1.23.1"
                cache: true
                cache-dependency-path: |
                  **/go.sum
                  **/go.mod
            - name: Resolve dependencies
              run: go mod download
            - name: Test
              run: go test -cover ./...

        

