name: Test

on:
  workflow_dispatch:

permissions: {}

jobs:
    golangci:
        permissions:
            contents: read
            actions: read
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: "1.23.1"
                cache: true
                cache-dependency-path: |
                  **/go.sum
                  **/go.mod
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v8
              with:
                version: v2.1
    test:
        needs: golangci
        permissions:
            contents: read
            actions: read
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: "1.23.1"
                cache: true
                cache-dependency-path: |
                  **/go.sum
                  **/go.mod
            - name: Resolve dependencies
              run: go mod download
            - name: Test
              run: go test -cover ./...

        

